//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT2MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opportuniteit
    {
        public int OpportuniteitId { get; set; }
        public string Persoon_Id { get; set; }
        public System.DateTime Datum { get; set; }
        public System.DateTime Einddatum { get; set; }
        public string Omschrijving { get; set; }
    
        public virtual Persoon Persoon { get; set; }
    }
}
