//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT2MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persoon
    {
        public Persoon()
        {
            this.Verkopen = new HashSet<Verkoop>();
        }
    
        public int PersoonId { get; set; }
        public string KlantCode { get; set; }
        public string Aanspreking { get; set; }
        public string Voornaam { get; set; }
        public string Familienaam { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string Gemeente { get; set; }
        public string Land { get; set; }
        public string Telefoon { get; set; }
        public string Email { get; set; }
        public string Categorie_Code { get; set; }
        public Nullable<int> Bedrijf_Id { get; set; }
    
        public virtual Bedrijf Bedrijf { get; set; }
        public virtual Categorie Categorie { get; set; }
        public virtual Opportuniteit Opportuniteiten { get; set; }
        public virtual ICollection<Verkoop> Verkopen { get; set; }
    }
}
