//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT2MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.VerkoopRegels = new HashSet<VerkoopRegel>();
        }
    
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string Omschrijving { get; set; }
        public string Eenheid { get; set; }
        public decimal PrijsPerEenheid { get; set; }
    
        public virtual ICollection<VerkoopRegel> VerkoopRegels { get; set; }
    }
}
