//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECT2MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerkoopRegel
    {
        public int Verkoop_Id { get; set; }
        public int RegelNr { get; set; }
        public int Product_Id { get; set; }
        public int Aantal { get; set; }
        public Nullable<decimal> Korting { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Verkoop Verkoop { get; set; }
    }
}
